spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      host: thingdong.com
      port: 1234
      repositories:
        enabled: false
      timeout: 5000

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 
    username: 
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 10
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    com.bell.thingdong: debug
    org:
      hibernate: info

jwt:
  key: 

server:
  ec2-url: https://thingdong.com

translator:
  papago:
    url: 
    client-id: 
    client-secret: 

generator:
  stable-diffusion:
    url: https://thingdong.com/generate
