/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/nwYEiHrS9YGtJu34/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#fefefe']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Sphere 8"
            geometry={nodes['Sphere 8'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[-49.71, -12.2, 39.4]}
            rotation={[1.34, -0.49, 0.76]}
            scale={1}
          />
          <mesh
            name="Sphere 7"
            geometry={nodes['Sphere 7'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[36.58, 7.41, -26.1]}
            rotation={[1.34, 0.36, -2.25]}
            scale={1}
          />
          <mesh
            name="Sphere 6"
            geometry={nodes['Sphere 6'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[-33.44, 16.07, -32.9]}
            rotation={[1.86, -0.12, 2.78]}
            scale={1}
          />
          <mesh
            name="Sphere 5"
            geometry={nodes['Sphere 5'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[-13.62, 48.78, 27.79]}
            rotation={[1.03, -0.18, -0.31]}
            scale={1}
          />
          <mesh
            name="Sphere 4"
            geometry={nodes['Sphere 4'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[38.72, -41.43, 6.89]}
            rotation={[-2.65, 0.02, -1.13]}
            scale={1}
          />
          <mesh
            name="Sphere 3"
            geometry={nodes['Sphere 3'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[-62.89, 0.28, 7.57]}
            rotation={[1.51, 0.32, 1.66]}
            scale={1}
          />
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[-37.67, -51.86, -23.86]}
            rotation={[-3.14, 0.68, 0.46]}
            scale={1}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Mini Sphere']}
            castShadow
            receiveShadow
            position={[16.82, -13.15, 56.57]}
            rotation={[-0.14, -1.12, -1.74]}
            scale={1}
          />
          <mesh
            name="Bell_Q.004"
            geometry={nodes['Bell_Q.004'].geometry}
            material={nodes['Bell_Q.004'].material}
            castShadow
            receiveShadow
            position={[-15.48, -1.76, 8.13]}
            rotation={[-0.32, -0.17, -0.05]}
            scale={250}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-63.65, 260, 277]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
